name: 'Validates PR titles against Submitty guidelines'
description: 'Validates PR titles against Submitty guidelines'

branding:
  icon: 'check-square'
  color: 'blue'

runs:
  using: 'node12'
  main: 'dist/index.js'
